In [1]:
import torch
import torch.nn.functional as F
import numpy as np
import bitarray
#from pytorch_transformers import GPT2LMHeadModel, GPT2Tokenizer
from transformers import AutoModelForCausalLM, AutoTokenizer
#from transformers import CamembertLMHeadModel, CamembertTokenizer, CamembertForCausalLM, AutoTokenizer

import random

In [2]:
message_secret = "I am hidden"
message_secret = message_secret + '<eos>'

amorce = "I am going on a vacation to Italy. I am hoping that my"

model_name = "gpt2"

In [3]:
def limit_past(past):
    past = list(past)
    for i in range(len(past)):
        past[i] = past[i][:, :, :, -1022:]
    return past

def int2bits(inp, num_bits):
    if num_bits == 0:
        return []
    strlist = ('{0:0%db}' % num_bits).format(inp)
    return [int(strval) for strval in reversed(strlist)]

def num_same_from_beg(bits1, bits2):
    assert len(bits1) == len(bits2)
    for i in range(len(bits1)):
        if bits1[i] != bits2[i]:
            break

    return i

def bits2int(bits):
    res = 0
    for i, bit in enumerate(bits):
        res += bit * (2 ** i)
    return res

In [4]:
tokenizer = AutoTokenizer.from_pretrained(model_name)
#tokenizer = MeteorTokenizer.from_pretrained(model_name)
#tokenizer.unk_token = None
#tokenizer.bos_token = None
#tokenizer.eos_token = None

#model = GPT2LMHeadModel.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)
model.eval();

In [5]:
encoded_message = tokenizer.encode(message_secret)
encoded_context = tokenizer.encode(amorce)

print(amorce)
print(encoded_context)

print(message_secret)
print(encoded_message)

tensor_amorce = torch.LongTensor(encoded_context).view(1,-1)
tensor_message = torch.LongTensor(encoded_message).view(1,-1)
#liste des tokens visibles sur:
#https://s3.amazonaws.com/models.huggingface.co/bert/gpt2-vocab.json

I am going on a vacation to Italy. I am hoping that my
[40, 716, 1016, 319, 257, 14600, 284, 8031, 13, 314, 716, 7725, 326, 616]
I am hidden<eos>
[40, 716, 7104, 27, 68, 418, 29]


In [6]:
tokens_temp = encoded_context.copy()
tensor_tokens = torch.LongTensor(tokens_temp).view(1,-1)
for i in range(15):
    with torch.no_grad():
            outputs = model(tensor_tokens)
            logits, past = outputs.logits, outputs.past_key_values
            
            tokens_temp.append(logits[0,-1].argsort()[-1].item())
            tensor_tokens = torch.LongTensor(tokens_temp).view(1,-1)
print(tokens_temp)
print(tokenizer.decode(tokens_temp))

[40, 716, 1016, 319, 257, 14600, 284, 8031, 13, 314, 716, 7725, 326, 616, 3656, 481, 307, 1498, 284, 1282, 736, 2582, 13, 314, 716, 1016, 284, 307, 736]
I am going on a vacation to Italy. I am hoping that my wife will be able to come back soon. I am going to be back


In [7]:
tokens_temp = encoded_context.copy()
tensor_tokens = torch.LongTensor(tokens_temp).view(1,-1)

for i in range(20):
    with torch.no_grad():
            outputs = model(tensor_tokens)
            logits, past = outputs.logits, outputs.past_key_values
            
            tokens_temp.append(logits[0,-1].argsort()[-round(random.random()*10)-1].item())
            tensor_tokens = torch.LongTensor(tokens_temp).view(1,-1)
print(tokens_temp)
print(tokenizer.decode(tokens_temp))

[40, 716, 1016, 319, 257, 14600, 284, 8031, 13, 314, 716, 7725, 326, 616, 4957, 743, 307, 4642, 290, 4376, 612, 526, 366, 1026, 338, 655, 1165, 4923, 13, 383, 3514, 329, 262, 1641]
I am going on a vacation to Italy. I am hoping that my daughter may be born and raised there." "It's just too dangerous. The danger for the family


In [58]:
class ArithmeticEncoder:
    


    def __init__(self, **kwargs):
        self.tokenizer   = kwargs.get("tokenizer")
        self.precision   = kwargs.get("precision", 40)
        self.temperature = kwargs.get("temperature", 1)
        self.seed        = kwargs.get("seed", None)
        self.topk        = kwargs.get("topk", 60000)
        self.model       = kwargs.get("model")
        
        self.g         = torch.Generator(device="cpu")
        if self.seed is None:
            self.g.seed()
        else:
            self.g.manual_seed(self.seed)
        pass
    
    def limit_past(self, past):
        past = list(past)
        for i in range(len(past)):
            past[i] = past[i][:, :, :, -1022:]
        return past
    
    def step(self, current, past):
        outputs = self.model(current.unsqueeze(0), past_key_values=past)
        logits, past_keys = outputs.logits, outputs.past_key_values
        logits[0, -1, -1] = -1e20  # endoftext token can't happen
        logits[0, -1, 628] = -1e20  # 2 newlines token can't happen
        logits, indices = logits[0, -1, :].sort(descending=True)
        logits = logits.double()
        logits_temp = logits / self.temperature
        probs_temp = F.softmax(logits_temp, dim=0)
        
        return(probs_temp, past_keys, indices)

    def encode(self, message, context=None):

        if context is None:
            context = self.tokenizer.encode('<|endoftext|>')
        print(context)

        encoded_message = self.tokenizer.encode(message)
        context = torch.tensor(context, dtype=torch.long)
        # common BPE error case: 128, 128 (2 newlines) is interpretted as 628 (2 newlines)
        i = 0
        print(encoded_message)
        
        while i < len(encoded_message):
            if encoded_message[i] == 628:
                encoded_message[i] = 198
                encoded_message[i + 1:i + 1] = [198]
                i += 2
            else:
                i += 1

        max_val = 2 ** self.precision
        threshold = 2 ** (-self.precision)
        cur_interval = [0, max_val]  # bottom inclusive, top exclusive

        prev = context
        past_keys = None
        bit_message = []

        with torch.no_grad():
            i = 0
            while i < len(encoded_message):
                print(prev)
                probs_temp, past_keys, indices = self.step(prev, past_keys)
                cum_probs = probs_temp.cumsum(0)

                # Cutoff low probabilities that would be rounded to 0
                cur_int_range = cur_interval[1] - cur_interval[0]
                cur_threshold = 1 / cur_int_range
                print(cur_threshold)
                
                k = min(max(2, (probs_temp < cur_threshold).nonzero()[0].item()), self.topk)
                probs_temp_int = probs_temp[:k]  # Cutoff all but top k
                probs_temp_int = probs_temp_int / probs_temp_int.sum()  * cur_int_range

                # Round probabilities to integers given precision
                probs_temp_int = probs_temp_int.round().long()
                cum_probs = probs_temp_int.cumsum(0)

                # Remove any elements from the bottom if rounding caused the total prob to be too large
                overfill_index = (cum_probs > cur_int_range).nonzero()
                if len(overfill_index) > 0:
                    cum_probs = cum_probs[:overfill_index[0]]
                    k = overfill_index[0].item()

                # Add any mass to the top if removing/rounding causes the total prob to be too small
                cum_probs += cur_int_range - cum_probs[-1]  # add

                # Covnert to position in range
                cum_probs += cur_interval[0]

                rank = (indices == encoded_message[i]).nonzero().item()
                
                if rank >= k:
                    true_token_text = enc.decoder[inp[i]]
                    for rank_idx in range(k):
                        prop_token_text = enc.decoder[indices[rank_idx].item()]
                        # common case that is not caught
                        if inp[i] == 128 and indices[rank_idx] == 198:
                            rank = rank_idx
                            inp[i] = indices[rank_idx].item()
                            break

                        # Is there a more likely prefix token that could be the actual token generated?
                        if len(prop_token_text) <= len(true_token_text) and \
                                prop_token_text == true_token_text[:len(prop_token_text)]:
                            rank = rank_idx
                            suffix = true_token_text[len(prop_token_text):]
                            suffix_tokens = enc.encode(suffix)  # a list
                            inp[i] = indices[rank_idx].item()
                            inp[i + 1:i + 1] = suffix_tokens  # insert suffix tokens into list
                            break

                        # Is there a more likely longer token that could be the actual token generated?
                        elif len(prop_token_text) > len(true_token_text) and \
                                true_token_text == prop_token_text[:len(true_token_text)]:
                            whole_text = true_token_text
                            num_extra = 1
                            while len(whole_text) < len(prop_token_text):
                                whole_text += enc.decoder[inp[i + num_extra]]
                                num_extra += 1
                            if prop_token_text == whole_text[:len(prop_token_text)]:
                                rank = rank_idx
                                inp[i] = indices[rank_idx].item()
                                for j in range(1, num_extra):
                                    del inp[i + j]

                                if len(whole_text) > len(prop_token_text):
                                    suffix = whole_text[len(prop_token_text):]
                                    suffix_tokens = enc.encode(suffix)  # a list
                                    inp[i + 1:i + 1] = suffix_tokens  # insert suffix tokens into list
                                break
                    else:
                        print('Unable to fix BPE error: token received: %s=%d, text: %s' % (true_token_text, inp[i], text))
                        rank = 0
                    
                selection = rank

                # Calculate new range as ints
                new_int_bottom = cum_probs[selection - 1] if selection > 0 else cur_interval[0]
                new_int_top = cum_probs[selection]

                # Convert range to bits
                new_int_bottom_bits_inc = list(reversed(int2bits(new_int_bottom, self.precision)))
                new_int_top_bits_inc = list(
                    reversed(int2bits(new_int_top - 1, self.precision)))  # -1 here because upper bound is exclusive

                # Emit most significant bits which are now fixed and update interval
                num_bits_encoded = num_same_from_beg(new_int_bottom_bits_inc, new_int_top_bits_inc)
                if i == len(encoded_message) - 1:
                    new_bits = new_int_bottom_bits_inc
                else:
                    new_bits = new_int_top_bits_inc[:num_bits_encoded]
                bit_message += new_bits
                print(new_bits)

                new_int_bottom_bits = new_int_bottom_bits_inc[num_bits_encoded:] + [0] * num_bits_encoded
                new_int_top_bits = new_int_top_bits_inc[num_bits_encoded:] + [1] * num_bits_encoded

                cur_interval[0] = bits2int(reversed(new_int_bottom_bits))
                cur_interval[1] = bits2int(reversed(new_int_top_bits)) + 1  # +1 here because upper bound is exclusive
 
                # Update history with new token
                prev = torch.tensor([encoded_message[i]], dtype=torch.long)
                i += 1

        return bit_message

print(message_secret)
encoder = ArithmeticEncoder(model=model, tokenizer=tokenizer)
bit_message = bitarray.bitarray(encoder.encode(message_secret))
print("encoded message: ", bit_message)

I am hidden<eos>
[50256]
[40, 716, 7104, 27, 68, 418, 29]
tensor([50256])
9.094947017729282e-13
[0, 0, 1, 0]
tensor([40])
3.0938210371382067e-12
[0, 1]
tensor([716])
1.6333561215934485e-11
[1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1]
tensor([7104])
3.638922741518681e-12
[0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0]
tensor([27])
2.6092516876836965e-12
[1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0]
tensor([68])
5.047412821460467e-12
[1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
tensor([418])
1.2635066753028321e-12
[0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
encoded message:  bitarray('0010011000110111001011101010111111110100111101100100000010000010000000011110011001111100011100010000000000000')


In [59]:
ah = np.array([[0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [60]:
eh = [0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [61]:
print(len(bit_message), len(eh))

109 108


In [62]:
class ArithmeticDecoder:
    

    def __init__(self, **kwargs):
        self.tokenizer   = kwargs.get("tokenizer")
        self.precision   = kwargs.get("precision", 40)
        self.temperature = kwargs.get("temperature", 1)
        self.seed        = kwargs.get("seed", None)
        self.topk        = kwargs.get("topk", 60000)
        self.model       = kwargs.get("model")
        
        self.g         = torch.Generator(device="cpu")
        if self.seed is None:
            self.g.seed()
        else:
            self.g.manual_seed(self.seed)
        pass
    
    def limit_past(self, past):
        past = list(past)
        for i in range(len(past)):
            past[i] = past[i][:, :, :, -1022:]
        return past
    
    def step(self, current, past):
        outputs = self.model(current.unsqueeze(0), past_key_values=past)
        logits, past_keys = outputs.logits, outputs.past_key_values
        logits[0, -1, -1] = -1e20  # endoftext token can't happen
        logits[0, -1, 628] = -1e20  # 2 newlines token can't happen
        logits, indices = logits[0, -1, :].sort(descending=True)
        logits = logits.double()
        logits_temp = logits / self.temperature
        probs_temp = F.softmax(logits_temp, dim=0)
        
        return(probs_temp, past_keys, indices)
    
    def decode(self, message, context=None, finish_sent=False):
        if context is None:
            context = self.tokenizer.encode('<|endoftext|>')
            
        max_val = 2 ** self.precision
        threshold = 2 ** (- self.precision)
        cur_interval = [0, max_val]  # bottom inclusive, top exclusive
            
        context = torch.tensor(context, dtype=torch.long)

        prev = context
        output = context
        past_keys = None
        
        with torch.no_grad():
            i = 0
            sent_finish = False
            while i < len(message) or (finish_sent and not sent_finish):
                probs, past_keys, indices = self.step(prev, past_keys)
                print('z est reparti : ', probs.cumsum(0)[:10], cur_interval[0], cur_interval[1])

                # conditions for having reached the end of the message
                if i >= len(message):
                    selection = 0
                    sent_finish = is_sent_finish(indices[selection].item(), enc)
                else:
                    # Cutoff low probabilities that would be rounded to 0
                    cur_int_range = cur_interval[1] - cur_interval[0]
                    cur_threshold = 1 / cur_int_range    
                    k = min(max(2, (probs < cur_threshold).nonzero()[0].item()), self.topk)
                    probs_temp_int = probs[:k]  # Cutoff all but top k

                    # Rescale to correct range
                    probs_temp_int = probs/probs.sum() * cur_int_range

                    # Round probabilities to integers given precision
                    probs_temp_int = probs_temp_int.round().long()
                    cum_probs = probs_temp_int.cumsum(0)

                    # Remove any elements from the bottom if rounding caused the total prob to be too large
                    overfill_index = (cum_probs > cur_int_range).nonzero()
                    if len(overfill_index) > 0:
                        cum_probs = cum_probs[:overfill_index[0]]

                    # Add any mass to the top if removing/rounding causes the total prob to be too small
                    cum_probs += cur_int_range - cum_probs[-1]  # add

                    # Get out resulting probabilities
                    probs_final = cum_probs.clone()
                    probs_final[1:] = cum_probs[1:] - cum_probs[:-1]

                    # Convert to position in range
                    cum_probs += cur_interval[0]

                    # Get selected index based on binary fraction from message bits
                    message_bits = message[i:i + self.precision]
                    if i + self.precision > len(message):
                        message_bits = message_bits + [0] * (i + self.precision - len(message))
                    message_idx = bits2int(reversed(message_bits))
                    selection = (cum_probs > message_idx).nonzero()[0].item()
         
                    # Calculate new range as ints
                    new_int_bottom = cum_probs[selection - 1] if selection > 0 else cur_interval[0]
                    new_int_top = cum_probs[selection]

                    # Convert range to bits
                    new_int_bottom_bits_inc = list(reversed(int2bits(new_int_bottom, self.precision)))
                    new_int_top_bits_inc = list(
                        reversed(int2bits(new_int_top - 1, self.precision)))  # -1 here because upper bound is exclusive
                    # Consume most significant bits which are now fixed and update interval
                    num_bits_encoded = num_same_from_beg(new_int_bottom_bits_inc, new_int_top_bits_inc)
                    i += num_bits_encoded

                    new_int_bottom_bits = new_int_bottom_bits_inc[num_bits_encoded:] + [0] * num_bits_encoded
                    new_int_top_bits = new_int_top_bits_inc[num_bits_encoded:] + [1] * num_bits_encoded

                    cur_interval[0] = bits2int(reversed(new_int_bottom_bits))
                    cur_interval[1] = bits2int(reversed(new_int_top_bits)) + 1  # +1 here because upper bound is exclusive


                # Update history with new token
                prev = indices[selection].view(1)
                output = torch.cat((output, prev))

                # For text->bits->text
                partial = self.tokenizer.decode(output[len(context):].tolist())
                print(indices[:5])
                print("==========================================")
                print("==========================================")
                if '<eos>' in partial:
                    break
                
                print(selection, partial)
        return output[len(context):].tolist()

    
decoder = ArithmeticDecoder(model=model, tokenizer=tokenizer, topk=60000)
print(eh[0])
bit_message_2 = bitarray.bitarray(eh)
decoded_message = decoder.decode(bit_message)


print(message_secret)
print(encoded_message)
print("decoded message: ",decoded_message)
print(tokenizer.decode(decoded_message))

0
z est reparti :  tensor([0.0625, 0.1003, 0.1245, 0.1439, 0.1623, 0.1739, 0.1852, 0.1944, 0.2031,
        0.2109], dtype=torch.float64) 0 1099511627776
tensor([198, 464,   1,  32,  40])
4 I
z est reparti :  tensor([0.0934, 0.1815, 0.2446, 0.2920, 0.3389, 0.3677, 0.3938, 0.4166, 0.4380,
        0.4543], dtype=torch.float64) 332922693904 656147595408
tensor([1101, 1053,  423,  716,  373])
3 I am
z est reparti :  tensor([0.1394, 0.2198, 0.2520, 0.2804, 0.3054, 0.3279, 0.3497, 0.3712, 0.3910,
        0.4082], dtype=torch.float64) 548452273768 609675909364
tensor([ 257,  407, 1016,  281,  523])
7330 I am hidden
z est reparti :  tensor([0.2105, 0.3517, 0.4276, 0.4980, 0.5351, 0.5698, 0.6009, 0.6282, 0.6550,
        0.6795], dtype=torch.float64) 279195942912 554002546688
tensor([ 287,  422, 2157, 1497,  416])
2843 I am hidden xx
z est reparti :  tensor([0.1551, 0.2144, 0.2455, 0.2692, 0.2863, 0.3033, 0.3177, 0.3299, 0.3407,
        0.3507], dtype=torch.float64) 530565562368 892823404544
tens

In [13]:
decoder = ArithmeticDecoder(model=model, tokenizer=tokenizer, topk=60000)
decoded_message = decoder.decode(encoded_message, context=encoded_context)
print("decoded message: ",decoded_message)
print(tokenizer.decode(decoded_message))

encoder = ArithmeticEncoder(model=model, tokenizer=tokenizer, topk=60000)
encoded_message = encoder.encode(message_secret, contexte=encoded_context)
print("encoded message: ",encoded_message)

decoder = ArithmeticDecoder(model=model, tokenizer=tokenizer, topk=60000)
decoded_message = decoder.decode(encoded_message)
print("decoded message: ",decoded_message)
print(tokenizer.decode(decoded_message))

z est reparti :  tensor([0.0824, 0.1287, 0.1568, 0.1798, 0.2009, 0.2190, 0.2364, 0.2536, 0.2696,
        0.2825], dtype=torch.float64) 0 1099511627776


IndexError: index 0 is out of bounds for dimension 0 with size 0

In [ ]:
print(amorce, message_secret)
#bit2str(encoded_message, model, tokenizer)[:-5]
#str2bits(model=model, enc=tokenizer, message=message_secret)
#decoded_message = bit2str(encoded_message, model, tokenizer)[:-5]
encoded_message = str2bits(model=model, enc=tokenizer, message=message_secret)
print(encoded_message)

In [ ]:
def is_sent_finish(token_idx, enc):
    token = enc.decode(token_idx)
    print(token)
    return '.' in token or '!' in token or '?' in token

def StegaGen(method, tokenizer, model, proc_seed): 
    
    if method == 'arithmetic':
        encoder_decoder = ArithmeticStega(tokenizer=tokenizer, model=model, seed=proc_seed) 
        
    elif method == 'adg':
        encoder_decoder = ArithmeticStega(tokenizer=tokenizer,model=model, seed=proc_seed)   
    else:
        print('Unkown method: ', method)
        
    return(encoder_decoder)


class ArithmetiEncoder:

    def __init__(self, **kwargs):
        self.tokenizer = tokenizer
        self.precision = kwargs.get("precision", 32)
        self.seed      = kwargs.get("seed", None)
        self.topk      = kwargs.get("topk", 10)
        self.topp      = kwargs.get("topp", None)
        self.model     = kwargs.get("model")
        
        self.g         = torch.Generator(device="cpu")
        if self.seed is None:
            self.g.seed()
        else:
            self.g.manual_seed(self.seed)
        pass
    
    def reset(self, context):
        return self.step(context, None)
    
    def reajust_probs(self, logits, indices):
        probs = F.softmax(logits , dim=0)
        if self.topp is not None:
            overfill_index = ((probs.cumsum(0) > self.topp).nonzero())[0]
            reajusted_probs = probs[:overfill_index]
            reajusted_indices = indices[:overfill_index]
        elif self.topk is not None:
            reajusted_probs = probs[:self.topk]
            reajusted_indices = indices[:self.topk]
        return(F.softmax(reajusted_probs , dim=0), reajusted_indices)
    
    def step(self, current, past):
        outputs = self.model(current.unsqueeze(0), past_key_values=past)
        logits, past_keys = outputs.logits, outputs.past_key_values
        
        logits[0, -1, -1] = -1e20  # endoftext token can't happen
        logits[0, -1, 628] = -1e20  # 2 newlines token can't happen
        logits, indices = logits[0, -1, :].sort(descending=True)
        
        probs, indices = self.reajust_probs(logits, indices)
        
        return(probs, past_keys, indices)
        
    def encode(self, private_message_bit: bitarray.bitarray, context: str = None):
        """
        :param msg: np array of 0s and 1s constituting a message bitstring
        :return:
        """
        message = private_message_bit
        tokenizer = self.tokenizer
        precision = self.precision

        max_val = 2 ** precision
        cur_interval = [0, max_val]  # bottom inclusive, top exclusive

        prev = context
        print("context is ", context)
        enc_prev = torch.LongTensor(tokenizer.encode(context))
        
        _, _, _ = self.reset(enc_prev)

        with torch.no_grad():
            i = 0
            j = 0
            past=None
            sent_finish = False
            while i < len(message) or (not sent_finish):

                probs, past, indices = self.step(enc_prev, past)
                          
                j += 1
                probs_temp = probs

                # conditions for having reached the end of the message
                if i >= len(message):
                    token = tokenizer.decode(token_idx)
                    sent_finish = '.' in token or '!' in token or '?' in token
                    print("token: ", token,"sent_finish: ",  sent_finish)
                else:
                    # Cutoff low probabilities that would be rounded to 0
                    cur_int_range = cur_interval[1] - cur_interval[0]

                    # Rescale to correct range
                    probs_temp_int = probs_temp * cur_int_range

                    # Round probabilities to integers given precision
                    probs_temp_int = probs_temp_int.round().long()
                    cum_probs = probs_temp_int.cumsum(0)
                    
                    # Remove any elements from the bottom if rounding caused the total prob to be too large
                    overfill_index = (cum_probs > cur_int_range).nonzero()
                    print(overfill_index, "uh")
                    if len(overfill_index) > 0:
                        cum_probs = cum_probs[:overfill_index[0]]

                    print(cum_probs[-1], "ah")
                    # Add any mass to the top if removing/rounding causes the total prob to be too small
                    cum_probs += cur_int_range - cum_probs[-1]  # add

                    # Get out resulting probabilities
                    probs_final = cum_probs.clone()
                    probs_final[1:] = cum_probs[1:] - cum_probs[:-1]

                    # Convert to position in range
                    cum_probs += cur_interval[0]

                    # Get selected index based on binary fraction from message bits
                    message_bits = message[i:i + precision]
                    if i + precision > len(message):
                        message_bits = message_bits + [0] * (i + precision - len(message))
                    message_idx = bits2int(reversed(message_bits))
                    selection = (cum_probs > message_idx).nonzero()[0].item()
                    
                    # Calculate new range as ints
                    new_int_bottom = cum_probs[selection - 1] if selection > 0 else cur_interval[0]
                    new_int_top = cum_probs[selection]

                    # Convert range to bits
                    new_int_bottom_bits_inc = list(reversed(int2bits(new_int_bottom, precision)))
                    new_int_top_bits_inc = list(reversed(int2bits(new_int_top - 1, precision)))  
                    # -1 here because upper bound is exclusive

                    # Consume most significant bits which are now fixed and update interval
                    num_bits_encoded = num_same_from_beg(new_int_bottom_bits_inc, new_int_top_bits_inc)
                    i += num_bits_encoded

                    new_int_bottom_bits = new_int_bottom_bits_inc[num_bits_encoded:] + [0] * num_bits_encoded
                    new_int_top_bits = new_int_top_bits_inc[num_bits_encoded:] + [1] * num_bits_encoded

                    cur_interval[0] = bits2int(reversed(new_int_bottom_bits))
                    cur_interval[1] = bits2int(reversed(new_int_top_bits)) + 1  
                    # +1 here because upper bound is exclusive

                    q = probs_final.double() / probs_final.sum()

                # Update history with new token
                prev = indices[selection].view(1)
                
                enc_prev = torch.cat((enc_prev, prev))
                print("current message: ", tokenizer.decode(enc_prev), prev, selection)

                # For text->bits->text
                partial = self.tokenizer.decode(enc_prev[len(context):].tolist())
                if '<eos>' in partial:
                    break


        return self.medium.enc.decode(enc_prev[len(context):].tolist()), enc_prev[len(context):].tolist()




In [ ]:
seed = -1
proc_seed = (seed * 55555) % 77777
proc_rng = np.random.default_rng(proc_seed)

# Now branch into different methods
encoder_decoder = StegaGen('arithmetic', tokenizer, model, proc_seed)

print(encoded_message, amorce)
ah = model( torch.LongTensor(tokenizer.encode(amorce)).unsqueeze(0)  )
logits=  ah.logits
print(logits.argmax())

# Proceed with communication
public_message_str, public_message_token = encoder_decoder.encode(private_message_bit=encoded_message,context=amorce)
print(public_message_str)

In [ ]:
    def decode(self, public_message_token, text=None, context: str = None, private_message_bitlen=None, **kwargs):

        inp = public_message_token
        enc = self.medium.enc
        device = self.medium.device  # may want to restrict to CPU!
        precision = self.precision
        max_val = 2 ** precision

        max_val = 2 ** precision
        cur_interval = [0, max_val]  # bottom inclusive, top exclusive
        
        t_iter_1 = None

        enc_context = self.medium.encode_context(context)
        enc_context = th.tensor(enc_context[-1022:], device=device, dtype=th.long)
        prev = enc_context
        message = []
        with th.no_grad():
            i = 0
            j = 0
            while i < len(inp):

                if t_iter_1 is not None:
                    delta_t_step_no_medium = time.time() - t_iter_1
                t_medium_1 = time.time()

                if j == 0:
                    probs, info = self.medium.reset(context=context)
                else:
                    probs, info = self.medium.step(prev)
                j += 1
                probs = th.from_numpy(probs.astype(np.float64))

                delta_t_medium = time.time() - t_medium_1
                t_iter_1 = time.time()

                probs_temp = probs
                indices = th.from_numpy(info["indices"])
                probs_temp_int = probs_temp

                # Cutoff low probabilities that would be rounded to 0
                cur_int_range = cur_interval[1] - cur_interval[0]

                # Rescale to correct range
                probs_temp_int = probs_temp_int / probs_temp_int.sum() * cur_int_range

                # Round probabilities to integers given precision
                probs_temp_int = probs_temp_int.round().long()
                cum_probs = probs_temp_int.cumsum(0)

                # Remove any elements from the bottom if rounding caused the total prob to be too large
                overfill_index = (cum_probs > cur_int_range).nonzero()
                if len(overfill_index) > 0:
                    cum_probs = cum_probs[:overfill_index[0]]
                    k = overfill_index[0].item()

                # Add any mass to the top if removing/rounding causes the total prob to be too small
                cum_probs += cur_int_range - cum_probs[-1]  # add

                # Covnert to position in range
                cum_probs += cur_interval[0]

                rank = (indices == inp[i]).nonzero().item()

                k = len(probs)
                # Handle most errors that could happen because of BPE with heuristic
                if rank >= k:
                    true_token_text = enc.decoder[inp[i]]
                    for rank_idx in range(k):
                        prop_token_text = enc.decoder[indices[rank_idx].item()]
                        # common case that is not caught
                        if inp[i] == 128 and indices[rank_idx] == 198:
                            rank = rank_idx
                            inp[i] = indices[rank_idx].item()
                            break

                        # Is there a more likely prefix token that could be the actual token generated?
                        if len(prop_token_text) <= len(true_token_text) and \
                                prop_token_text == true_token_text[:len(prop_token_text)]:
                            rank = rank_idx
                            suffix = true_token_text[len(prop_token_text):]
                            suffix_tokens = enc.encode(suffix)  # a list
                            inp[i] = indices[rank_idx].item()
                            inp[i + 1:i + 1] = suffix_tokens  # insert suffix tokens into list
                            break

                        # Is there a more likely longer token that could be the actual token generated?
                        elif len(prop_token_text) > len(true_token_text) and \
                                true_token_text == prop_token_text[:len(true_token_text)]:
                            whole_text = true_token_text
                            num_extra = 1
                            while len(whole_text) < len(prop_token_text):
                                whole_text += enc.decoder[inp[i + num_extra]]
                                num_extra += 1
                            if prop_token_text == whole_text[:len(prop_token_text)]:
                                rank = rank_idx
                                inp[i] = indices[rank_idx].item()
                                for j in range(1, num_extra):
                                    del inp[i + j]

                                if len(whole_text) > len(prop_token_text):
                                    suffix = whole_text[len(prop_token_text):]
                                    suffix_tokens = enc.encode(suffix)  # a list
                                    inp[i + 1:i + 1] = suffix_tokens  # insert suffix tokens into list
                                break
                    else:
                        print('Unable to fix BPE error: token received: %s=%d, text: %s' % (
                            true_token_text, inp[i], text))
                        rank = 0

                selection = rank

                # Calculate new range as ints
                new_int_bottom = cum_probs[selection - 1] if selection > 0 else cur_interval[0]
                new_int_top = cum_probs[selection]

                # Convert range to bits
                new_int_bottom_bits_inc = list(reversed(int2bits(new_int_bottom, precision)))
                new_int_top_bits_inc = list(reversed(int2bits(new_int_top - 1, precision)))  
                # -1 because upper bound is exclusive

                # Emit most significant bits which are now fixed and update interval
                num_bits_encoded = num_same_from_beg(new_int_bottom_bits_inc, new_int_top_bits_inc)
                if i == len(inp) - 1:
                    new_bits = new_int_bottom_bits_inc
                else:
                    new_bits = new_int_top_bits_inc[:num_bits_encoded]
                message += new_bits

                new_int_bottom_bits = new_int_bottom_bits_inc[num_bits_encoded:] + [0] * num_bits_encoded
                new_int_top_bits = new_int_top_bits_inc[num_bits_encoded:] + [1] * num_bits_encoded

                cur_interval[0] = bits2int(reversed(new_int_bottom_bits))
                cur_interval[1] = bits2int(reversed(new_int_top_bits)) + 1  
                # +1 because upper bound is exclusive

                # Update history with new token
                prev = th.tensor([inp[i]], device=device, dtype=th.long)
                i += 1

        output = bitarray.bitarray(message)
        if private_message_bitlen is not None:
            output = output[:private_message_bitlen]
        return output
